apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: aud2-oct24-1 
  janus-idp.io/tekton: aud2-oct24-1
  backstage.io/kubernetes-id: aud2-oct24-1
  backstage.io/kubernetes-namespace: aud2-oct24-1 
  app.kubernetes.io/part-of: aud2-oct24-1
resources: 
- application-dev.yaml