apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: aud2-oct24-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aud2-oct24-1 
  name: aud2-oct24-1
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: aud2-oct24-1 
    weight: 100 
  wildcardPolicy: None
